export const LOG_REFLECTOR_OPTIONS = 'LOG_REFLECTOR_OPTIONS';
export const LOG_REFLECTOR_OPTIONS_FACTORY = 'LOG_REFLECTOR_OPTIONS_FACTORY';
export const LOG_REFLECTOR_SENSITIVE = 'LOG_REFLECTOR_SENSITIVE';
